print "P41_PO105_A30_FULL_CLASS";
Q<Z> := PolynomialRing(Rationals());
C := HyperellipticCurve((Z^2-218)*(Z^2-338)*(Z^2-458));
Hk, AtoHk := TwoCoverDescent(C);
A<theta> := Domain(AtoHk);
delta := 71283/3094-theta;
print "SELMER_SIZE", #Hk;
print "SELMER_SET", Hk;
print "DELTA_IMAGE", AtoHk(delta);
print "DELTA", delta;
print "STATUS DONE";
